INSERT INTO `projects` (`name`,`private`) VALUES ('nonummy','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('felis.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('interdum feugiat.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Cum','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('quam vel','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('viverra. Maecenas','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('a, facilisis non,','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('amet ante.','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('egestas,','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('In scelerisque','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('convallis convallis','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('non sapien','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('tortor, dictum eu,','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Proin','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('sagittis felis. Donec','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('fermentum vel, mauris.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('venenatis','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('urna.','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('metus. In nec','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('gravida','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Nulla tempor augue','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('cubilia Curae;','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('dis parturient montes,','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('montes, nascetur ridiculus','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('iaculis','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Aenean egestas hendrerit','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('nunc','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('et, euismod','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('magnis','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('at','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('sed turpis nec','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('dui. Cras','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Duis risus','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('semper','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('posuere cubilia Curae;','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('suscipit','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Fusce','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('neque pellentesque massa','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('turpis. In condimentum.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Vestibulum ante','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('bibendum.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('laoreet ipsum. Curabitur','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Aliquam','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('venenatis','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('est ac','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('est. Nunc ullamcorper,','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('id enim. Curabitur','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('et','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Donec tempus, lorem','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Cum sociis natoque','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('ut lacus. Nulla','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('tincidunt','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Vivamus sit amet','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('sit amet','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('semper tellus id','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Curae; Donec','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('mattis semper,','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Quisque imperdiet, erat','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('ipsum cursus','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('felis','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Class aptent','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('id','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('porttitor interdum. Sed','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('et nunc. Quisque','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('non quam.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('tortor nibh sit','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('tincidunt vehicula risus.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('metus vitae','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('nec tellus.','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('diam vel arcu.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('et, eros.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Nulla eget metus','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('lorem ut aliquam','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('neque','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('nibh. Donec','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('lectus pede et','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('facilisis, magna tellus','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('interdum.','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('vulputate mauris','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('porttitor','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Sed pharetra,','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('ac mattis semper,','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('Nullam nisl. Maecenas','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('justo. Proin','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('ut, pellentesque eget,','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Nullam','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('risus, at fringilla','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('nunc, ullamcorper','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('auctor non, feugiat','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('arcu. Curabitur ut','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('consectetuer','0');
INSERT INTO `projects` (`name`,`private`) VALUES ('amet','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('nisi','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('at','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('dignissim tempor arcu.','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('tempor arcu.','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('libero','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('Phasellus fermentum','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('elit sed consequat','1');
INSERT INTO `projects` (`name`,`private`) VALUES ('gravida molestie arcu.','0');
