INSERT INTO projects (name, private) VALUES
("Nonummy",1),
("Felis",0),
("Interdum Feugiat",0),
("Cum",1),
("Quam Vel",1),
("Viverra Maecenas",0),
("A, Facilisis Non,",1),
("Amet Ante",1),
("Egestas,",0),
("In Scelerisque",1),
("Convallis Convallis",1),
("Non Sapien",0),
("Tortor, Dictum Eu,",0),
("Proin",0),
("Sagittis Felis Donec",1),
("Fermentum Vel, Mauris",0),
("Venenatis",0),
("Urna",1),
("Metus In Nec",1),
("Gravida",1),
("Nulla Tempor Augue",1),
("Cubilia Curae;",0),
("Dis Parturient Montes,",1),
("Montes, Nascetur Ridiculu",1),
("Iaculis",0),
("Aenean Egestas Hendrerit",0),
("Nunc",1),
("Et, Euismod",1),
("Magnis",1),
("At",0),
("Sed Turpis Nec",1),
("Dui Cras",0),
("Duis Risus",1),
("Semper",1),
("Posuere Cubilia Curae;",0),
("Suscipit",1),
("Fusce",1),
("Neque Pellentesque Massa",0),
("Turpis In Condimentum",0),
("Vestibulum Ante",1),
("Bibendum",0),
("Laoreet Ipsum Curabitur",1),
("Aliquam",1),
("Venenatis",0),
("Est Ac",1),
("Est Nunc Ullamcorper,",1),
("Id Enim Curabitur",0),
("Et",1),
("Donec Tempus, Lorem",1),
("Cum Sociis Natoque",0),
("Ut Lacus Nulla",1),
("Tincidunt",1),
("Vivamus Sit Amet",0),
("Sit Amet",1),
("Semper Tellus Id",0),
("Curae; Donec",1),
("Mattis Semper,",1),
("Quisque Imperdiet, Erat",1),
("Ipsum Cursus",0),
("Felis",1),
("Class Aptent",0),
("Id",0),
("Porttitor Interdum Sed",0),
("Et Nunc Quisque",0),
("Non Quam",0),
("Tortor Nibh Sit",1),
("Tincidunt Vehicula Risus",0),
("Metus Vitae",0),
("Nec Tellus",1),
("Diam Vel Arcu",0),
("Et, Eros",0),
("Nulla Eget Metus",0),
("Lorem Ut Aliquam",0),
("Neque",0),
("Nibh Donec",0),
("Lectus Pede Et",1),
("Facilisis, Magna Tellus",1),
("Interdum",0),
("Vulputate Mauris",1),
("Porttitor",0),
("Sed Pharetra,",0),
("Ac Mattis Semper,",0),
("Nullam Nisl Maecenas",1),
("Justo Proin",1),
("Ut, Pellentesque Eget,",1),
("Nullam",1),
("Risus, At Fringilla",0),
("Nunc, Ullamcorper",0),
("Auctor Non, Feugiat",1),
("Arcu Curabitur Ut",0),
("Consectetuer",0),
("Amet",1),
("Nisi",1),
("At",1),
("Dignissim Tempor Arcu",1),
("Tempor Arcu",1),
("Libero",1),
("Phasellus Fermentum",1),
("Elit Sed Consequat",1),
("Gravida Molestie Arcu",0);