UPDATE `projects` SET `description` = 'Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu' WHERE `id` = 1;
UPDATE `projects` SET `description` = 'ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc' WHERE `id` = 2;
UPDATE `projects` SET `description` = 'et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit,' WHERE `id` = 3;
UPDATE `projects` SET `description` = 'massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat,' WHERE `id` = 4;
UPDATE `projects` SET `description` = 'nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum' WHERE `id` = 5;
UPDATE `projects` SET `description` = 'id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus.' WHERE `id` = 6;
UPDATE `projects` SET `description` = 'magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna' WHERE `id` = 7;
UPDATE `projects` SET `description` = 'non arcu. Vivamus sit amet risus. Donec egestas.' WHERE `id` = 8;
UPDATE `projects` SET `description` = 'nulla at sem molestie sodales. Mauris blandit' WHERE `id` = 9;
UPDATE `projects` SET `description` = 'metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget,' WHERE `id` = 10;
UPDATE `projects` SET `description` = 'Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus' WHERE `id` = 11;
UPDATE `projects` SET `description` = 'semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec,' WHERE `id` = 12;
UPDATE `projects` SET `description` = 'ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim' WHERE `id` = 13;
UPDATE `projects` SET `description` = 'euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum' WHERE `id` = 14;
UPDATE `projects` SET `description` = 'fermentum risus, at fringilla purus mauris a nunc. In at pede.' WHERE `id` = 15;
UPDATE `projects` SET `description` = 'quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum' WHERE `id` = 16;
UPDATE `projects` SET `description` = 'at pretium aliquet, metus urna convallis erat, eget tincidunt dui' WHERE `id` = 17;
UPDATE `projects` SET `description` = 'non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat.' WHERE `id` = 18;
UPDATE `projects` SET `description` = 'massa. Integer vitae nibh. Donec est mauris, rhoncus id,' WHERE `id` = 19;
UPDATE `projects` SET `description` = 'massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus.' WHERE `id` = 20;
UPDATE `projects` SET `description` = 'Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae,' WHERE `id` = 21;
UPDATE `projects` SET `description` = 'rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam.' WHERE `id` = 22;
UPDATE `projects` SET `description` = 'scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque' WHERE `id` = 23;
UPDATE `projects` SET `description` = 'lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur' WHERE `id` = 24;
UPDATE `projects` SET `description` = 'felis orci, adipiscing non, luctus sit amet, faucibus ut,' WHERE `id` = 25;
UPDATE `projects` SET `description` = 'diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus' WHERE `id` = 26;
UPDATE `projects` SET `description` = 'ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum' WHERE `id` = 27;
UPDATE `projects` SET `description` = 'blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer' WHERE `id` = 28;
UPDATE `projects` SET `description` = 'commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus' WHERE `id` = 29;
UPDATE `projects` SET `description` = 'blandit enim consequat purus. Maecenas libero est, congue' WHERE `id` = 30;
UPDATE `projects` SET `description` = 'in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean' WHERE `id` = 31;
UPDATE `projects` SET `description` = 'euismod ac, fermentum vel, mauris. Integer sem elit,' WHERE `id` = 32;
UPDATE `projects` SET `description` = 'Etiam bibendum fermentum metus. Aenean sed pede nec' WHERE `id` = 33;
UPDATE `projects` SET `description` = 'diam. Duis mi enim, condimentum eget, volutpat' WHERE `id` = 34;
UPDATE `projects` SET `description` = 'diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus' WHERE `id` = 35;
UPDATE `projects` SET `description` = 'lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci.' WHERE `id` = 36;
UPDATE `projects` SET `description` = 'vehicula. Pellentesque tincidunt tempus risus. Donec egestas.' WHERE `id` = 37;
UPDATE `projects` SET `description` = 'In lorem. Donec elementum, lorem ut aliquam' WHERE `id` = 38;
UPDATE `projects` SET `description` = 'sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id,' WHERE `id` = 39;
UPDATE `projects` SET `description` = 'placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo.' WHERE `id` = 40;
UPDATE `projects` SET `description` = 'semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet' WHERE `id` = 41;
UPDATE `projects` SET `description` = 'diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit' WHERE `id` = 42;
UPDATE `projects` SET `description` = 'justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum.' WHERE `id` = 43;
UPDATE `projects` SET `description` = 'tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet' WHERE `id` = 44;
UPDATE `projects` SET `description` = 'per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque' WHERE `id` = 45;
UPDATE `projects` SET `description` = 'magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu' WHERE `id` = 46;
UPDATE `projects` SET `description` = 'diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna' WHERE `id` = 47;
UPDATE `projects` SET `description` = 'lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi' WHERE `id` = 48;
UPDATE `projects` SET `description` = 'Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent' WHERE `id` = 49;
UPDATE `projects` SET `description` = 'amet, dapibus id, blandit at, nisi. Cum sociis natoque' WHERE `id` = 50;
UPDATE `projects` SET `description` = 'est ac mattis semper, dui lectus rutrum urna, nec luctus felis' WHERE `id` = 51;
UPDATE `projects` SET `description` = 'non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat' WHERE `id` = 52;
UPDATE `projects` SET `description` = 'Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra' WHERE `id` = 53;
UPDATE `projects` SET `description` = 'non arcu. Vivamus sit amet risus. Donec egestas. Aliquam' WHERE `id` = 54;
UPDATE `projects` SET `description` = 'erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi' WHERE `id` = 55;
UPDATE `projects` SET `description` = 'scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat' WHERE `id` = 56;
UPDATE `projects` SET `description` = 'pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim,' WHERE `id` = 57;
UPDATE `projects` SET `description` = 'eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed' WHERE `id` = 58;
UPDATE `projects` SET `description` = 'eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc' WHERE `id` = 59;
UPDATE `projects` SET `description` = 'a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean' WHERE `id` = 60;
UPDATE `projects` SET `description` = 'Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam' WHERE `id` = 61;
UPDATE `projects` SET `description` = 'mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum' WHERE `id` = 62;
UPDATE `projects` SET `description` = 'enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus.' WHERE `id` = 63;
UPDATE `projects` SET `description` = 'Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod' WHERE `id` = 64;
UPDATE `projects` SET `description` = 'dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim' WHERE `id` = 65;
UPDATE `projects` SET `description` = 'justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate,' WHERE `id` = 66;
UPDATE `projects` SET `description` = 'consequat enim diam vel arcu. Curabitur ut' WHERE `id` = 67;
UPDATE `projects` SET `description` = 'ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget' WHERE `id` = 68;
UPDATE `projects` SET `description` = 'Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla' WHERE `id` = 69;
UPDATE `projects` SET `description` = 'Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id,' WHERE `id` = 70;
UPDATE `projects` SET `description` = 'sed turpis nec mauris blandit mattis. Cras eget nisi dictum' WHERE `id` = 71;
UPDATE `projects` SET `description` = 'Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non' WHERE `id` = 72;
UPDATE `projects` SET `description` = 'ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit' WHERE `id` = 73;
UPDATE `projects` SET `description` = 'dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec' WHERE `id` = 74;
UPDATE `projects` SET `description` = 'ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla' WHERE `id` = 75;
UPDATE `projects` SET `description` = 'auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque' WHERE `id` = 76;
UPDATE `projects` SET `description` = 'dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui,' WHERE `id` = 77;
UPDATE `projects` SET `description` = 'Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci' WHERE `id` = 78;
UPDATE `projects` SET `description` = 'ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc' WHERE `id` = 79;
UPDATE `projects` SET `description` = 'dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus.' WHERE `id` = 80;
UPDATE `projects` SET `description` = 'rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et,' WHERE `id` = 81;
UPDATE `projects` SET `description` = 'turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer' WHERE `id` = 82;
UPDATE `projects` SET `description` = 'Donec dignissim magna a tortor. Nunc commodo' WHERE `id` = 83;
UPDATE `projects` SET `description` = 'Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque' WHERE `id` = 84;
UPDATE `projects` SET `description` = 'lectus justo eu arcu. Morbi sit amet massa.' WHERE `id` = 85;
UPDATE `projects` SET `description` = 'metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper' WHERE `id` = 86;
UPDATE `projects` SET `description` = 'lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum' WHERE `id` = 87;
UPDATE `projects` SET `description` = 'orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In' WHERE `id` = 88;
UPDATE `projects` SET `description` = 'Nunc ullamcorper, velit in aliquet lobortis, nisi nibh' WHERE `id` = 89;
UPDATE `projects` SET `description` = 'sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis' WHERE `id` = 90;
UPDATE `projects` SET `description` = 'non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis' WHERE `id` = 91;
UPDATE `projects` SET `description` = 'rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem' WHERE `id` = 92;
UPDATE `projects` SET `description` = 'dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque' WHERE `id` = 93;
UPDATE `projects` SET `description` = 'et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam' WHERE `id` = 94;
UPDATE `projects` SET `description` = 'Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus.' WHERE `id` = 95;
UPDATE `projects` SET `description` = 'egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae,' WHERE `id` = 96;
UPDATE `projects` SET `description` = 'eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien.' WHERE `id` = 97;
UPDATE `projects` SET `description` = 'nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum' WHERE `id` = 98;
UPDATE `projects` SET `description` = 'odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit,' WHERE `id` = 99;
UPDATE `projects` SET `description` = 'Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt,' WHERE `id` = 100;